import LocalizedStrings from "react-native-localization";

let strings = new LocalizedStrings({
	ru: {
		complete:
			"Ваша заявка отправлено модераторам. Оно будет опубликована в течение дня.",
		invalidEmail: "Неверный e-mail",
		confirmPassword: "Подтверждение пароля",
		passwordsDoNotMatch: "Пароля не совпадают!",
		collapse: "Свернуть",
		didNotFill: "Пожалуста заполните все поля!",
		oferta: "О приложении",
		pickTariff: "Выберите тариф",
		tariffs: "Тарифы",
		remember: "Запомнить",
		attention: "Внимание!",
		yes: "Да",
		removePrompt: "Вы точна хотите удалить это объявления?",
		remove: "Удалить",
		update: "Изменить",
		filter: "Фильтр",
		login: "Вход",
		myAnnouncements: "Мои объявления",
		organization: "Организация",
		cityServices: "Город услуги",
		responsiblePerson: "Ответственное лицо",
		address: "Адрес",
		saveSettings: "Сохранить настройки",
		accessLocation: "Приложению требуется доступ к вашему местоположению",
		cancel: "Отменить",
		good: "Хорошо",
		chooseCategory: "Выберите рубрику",
		chooseSubcategory: "Выберите подкатегорию",
		bargaining: "Торг уместен",
		finalPrice: "Окончательная цена",
		price: "Цена (суммы)",
		priceD: "Цена (доллары)",
		enterTitle: "Ввести заголовок",
		additionalFields: "Дополнительные поля",
		yourDescription: "Ваше описание",
		addPhoto: "Добавить фото",
		yourContacts: "Ваши контактные данные",
		cityOfService: "Город предоставления услуги",
		chooseArea: "Выберите район",
		email: "Почта (e-mail)",
		publish: "Опубликовать",
		active: "Активные",
		inActive: "Не активные",
		adsDoNotExist: "Объявления не существуют",
		correspendenceDoesNotExist: "Переписки не существуют",
		indicateOnTheMap: "Указать на карте",
		noFavorites: "Нет избранных",
		searchText: "Искать в тексте объявления",
		onlyPhoto: "Только с фото",
		tile: "Плитка",
		list: "Список",
		showAds: "Показать объявлений",
		fill: "Заполните поле",
		forgot: "Забыли пароль?",
		noAccount: "Всё ещё нет аккаунта?",
		checkIn: "Регистрация",
		withoutRegistration: "Войдите без регистрации",
		i: "Входя в раздел Мой профиль, вы ",
		agreement: "принимаете Условия использования приложения",
		balance: "Баланс",
		currentBalance: "Текущий счет",
		bonuses: "Бонусы",
		returns: "Возвраты",
		paymentAmount: "Выбрать сумму платежа",
		refill: "Пополнение счета",
		paymentMethod: "Выбрать способ оплаты",
		totalAmount: "Итоговая сумма",
		pay: "Оплатить",
		confirm: "Подтвердить",
		cardProduct: "Карточка товара",
		posted: "размещено",
		description: "Описание",
		salesDepartment: "Отдел продаж",
		showNumber: "Показать номер",
		showMore: "Показать ещё",
		authorAds: "Все объявления автора",
		similarAds: "Схожие объявления",
		featured: "Избранные",
		productsAndServices: "Товары и услуги",
		appoinments: "Назначения",
		companyType: "Выберите тип компании",
		new: "Новая",
		acting: "Действующая",
		name: "Имя / компания",
		password: "Пароль",
		agree:
			"Согласен с условиями пользования и с условиями конфиденциальности",
		servicesDoNotExist: "Сервисы пока не существуют",
		adStats: "Статистика объявлений",
		views: "Просмотры",
		messages: "Сообщения",
		weSentMessage:
			"Мы отправили сообщение на ваш телефон. Введите его, чтобы закончить регистрацию!",
		confirmationCode: "Код подтверждения",
		register: "Зарегистрируйтесь",
		myPage: "Моя страница",
		services: "Сервисы",
		logOut: "Выход",
		writeAMessage: "Напишите сообщение",
		companyRegistration: "Регистрация компании",
		numberConfirmation: "Подтверждение номера",
		addAd: "Добавляем объявление",
		userAds: "Объявления пользователя",
		allPosts: "Все сообщения",
		chooseSubcategory: "Выберите субкатегорию",
		featuredAds: "Избранные объявления",
		profileSettings: "Настройки профиля",
		editAd: "Редактировать объявление",
		online: "В сети",
		categoriesDoNotExist: "Категории не существует",
		welcome: "",
		propertyName: "",
		willNotBeShared:
			"Ваши личные данные и данные компании не будет передаваться третьым лицам",
		next: "Дальше",
		all: "Все"
	},
	uz: {
		complete:
			"Sizning e`loningiz qabul qilindi va moderatorlarga jo`natildi. E`loningiz bir ish kuni davomida partalimizda paydo boladi.",
		invalidEmail: "Noto`g`ri e-mail",
		confirmPassword: "Parolni tasdiqlash",
		passwordsDoNotMatch: "Parollar bir xil emas!",
		collapse: "Yashirish",
		didNotFill: "Iltimos hamma maydonlarni to`ldiring!",
		oferta: "Dastur haqida",
		pickTariff: "Tarifni tanlang",
		tariffs: "Tariflar",
		remember: "Eslab qolish",
		attention: "Diqqat!",
		yes: "Ha",
		removePrompt: "Siz elonni o'chirmoqchimisiz?",
		remove: "O'chirish",
		update: "Yangilash",
		filter: "Sozlamalar",
		login: "Kirish",
		myAnnouncements: "Mening e'lonlarim",
		organization: "Tashkilot",
		cityServices: "Xizmat shahri",
		responsiblePerson: "Javobgar shaxs",
		address: "Manzil",
		saveSettings: "Sozlamalarni saqlash",
		accessLocation: "Dastur uchun sizning joylashgan joyingiz lozim",
		cancel: "Bekor qilish",
		good: "Yaxshi",
		chooseCategory: "Rubrikani tanlang",
		chooseSubcategory: "Pastki kategoriyani tanlang",
		bargaining: "Narx kelishilgan",
		finalPrice: "So'ngi narx",
		price: "Narx (so'm)",
		priceD: "Narx (dollar)",
		enterTitle: "Sarlavhani kiriting",
		additionalFields: "Qo'shimcha maydon",
		yourDescription: "Sizning ta'rifingiz",
		addPhoto: "Rasm qo'shish",
		yourContacts: "Sizning kontakt ma'lumotlaringiz",
		cityOfService: "Xizmat taqdim etiladigan shahar",
		chooseArea: "Tumanni tanlang",
		email: "Pochta (e-mail)",
		publish: "Joylashtirish",
		active: "Faol",
		inActive: "Faol emas",
		adsDoNotExist: "E'lon mavjud emas",
		correspendenceDoesNotExist: "Yozishmalar mavjud emas",
		indicateOnTheMap: "Kartada ko'rsatish",
		noFavorites: "Tanlanganlar yo'q",
		searchText: "E'lon matnini qidirish",
		onlyPhoto: "Faqat rasm bilan",
		tile: "Plitka",
		list: "Ro'yxat",
		showAds: "E'lonlarni ko'rsatish",
		fill: "Maydonni to'ldiring",
		forgot: "Parolni unutdingizmi?",
		noAccount: "Hali ham akkauntingiz yo'qmi?",
		checkIn: "Ro'yxatdan o'tish",
		withoutRegistration: "Ro'yxatdan o'tmasdan kirish",
		i: "Mening profilim bo'limiga kirish orqali, siz ",
		agreement:
			"Dasturdan foydalanish shartlarini qabul qilgan hisoblanasiz",
		balance: "Balans",
		currentBalance: "Hozirgi balans",
		bonuses: "Bonuslar",
		returns: "Qaytimlar",
		paymentAmount: "To'lov miqdorini tanlash",
		refill: "Hisobni to'ldirish",
		paymentMethod: "To'lov turini tanlash",
		totalAmount: "Jami",
		pay: "To'lash",
		confirm: "Tasdiqlash",
		cardProduct: "Mahsulot kartasi",
		posted: "Joylandi",
		description: "Ta'rif",
		salesDepartment: "Savdo bo'limi",
		showNumber: "Raqamni ko'rsatish",
		showMore: "Yana ko'rsatish",
		authorAds: "Muallifning barcha e'lonlari",
		similarAds: "O'xshash e'lonlar",
		featured: "Tanlanganlar",
		productsAndServices: "Mahsulot va xizmatlar",
		appoinments: "Belgilashlar",
		companyType: "Tashkilot turini tanlang",
		new: "Yangi",
		acting: "Faoliyat yuritayotgan",
		name: "Ism / tashkilot nomi",
		password: "Parol",
		agree: "Men foydalanish shartlari va maxfiylik shartlariga roziman",
		servicesDoNotExist: "Xizmatlar hozircha mavjud emas",
		adStats: "E'lonlar statistikasi",
		views: "Ko'rishlar soni",
		messages: "Xabarlar",
		weSentMessage:
			"Biz sizning telefoningizga xabar yubordik. Ro'yxatdan o'tishni yakunlash uchun ushbu xabarni kiriting!",
		confirmationCode: "Tasdiqlov kodi",
		register: "Ro'yxatdan o'ting",
		myPage: "Mening sahifam",
		services: "Xizmatlar",
		logOut: "Chiqish",
		writeAMessage: "Xabar yozing",
		companyRegistration: "Tashkilotni ro'yxatdan o'tkazish",
		numberConfirmation: "Raqamni tasdiqlash",
		addAd: "E'lon qo'shamiz",
		userAds: "Foydalanuvchi e'lonlari",
		allPosts: "Barcha xabarlar",
		featuredAds: "Tanlangan e'lonlar",
		profileSettings: "Profil sozlamalari",
		editAd: "E'lonni o'zgartirish",
		online: "Tizimda",
		categoriesDoNotExist: "Kategoriyalar qo'shilmagan",
		all: "Barchasi"
	},
	en: {
		complete:
			"Your request has sent to moderators. It will be posted during one working day.",
		invalidEmail: "Invalid email",
		confirmPassword: "Confirm password",
		passwordsDoNotMatch: "Passwords do not match!",
		collapse: "Collapse",
		didNotFill: "Please fill all fields!",
		oferta: "About application",
		pickTariff: "Pick tariff",
		tariffs: "Tariffs",
		remember: "Remember",
		attention: "Attention!",
		yes: "Yes",
		removePrompt: "Do you really want to delete?",
		update: "Update",
		remove: "Delete",
		filter: "Filter",
		login: "Login",
		myAnnouncements: "My announcements",
		organization: "Organization",
		cityServices: "City Services",
		responsiblePerson: "Responsible person",
		address: "Address",
		saveSettings: "Save settings",
		accessLocation: "The app needs access to your location",
		cancel: "Cancel",
		good: "Good",
		chooseCategory: "Choose a category",
		chooseSubcategory: "Choose a subcategory",
		bargaining: "Bargaining is appropriate",
		finalPrice: "Final price",
		price: "Price (sum)",
		priceD: "Price (dollar)",
		enterTitle: "Enter a title",
		additionalFields: "Additional fields",
		yourDescription: "Your description",
		addPhoto: "Add a photo",
		yourContacts: "Your contact details",
		cityOfService: "City of service",
		chooseArea: "Choose area",
		email: "E-mail",
		publish: "Publish",
		active: "Active",
		inActive: "Not active",
		adsDoNotExist: "Ads do not exist",
		correspendenceDoesNotExist: "Correspondence does not exist",
		indicateOnTheMap: "Indicate on the map",
		noFavorites: "No favorites",
		searchText: "Search ad text",
		onlyPhoto: "Only with photo",
		tile: "Tile",
		list: "List",
		showAds: "Show ads",
		fill: "Fill in the field",
		forgot: "Forgot your password?",
		noAccount: "Still no account?",
		checkIn: "Check in",
		withoutRegistration: "Sign in without registration",
		i: "By entering the My profile section, you ",
		agreement: "accept the terms of use of the application",
		balance: "Balance",
		currentBalance: "Current balance",
		bonuses: "Bonuses",
		returns: "Returns",
		paymentAmount: "Choose payment amount",
		refill: "Refill",
		paymentMethod: "Choose a payment method",
		totalAmount: "Total amount",
		pay: "Pay",
		confirm: "Confirm",
		cardProduct: "Card Product",
		posted: "Posted",
		description: "Description",
		salesDepartment: "Sales department",
		showNumber: "Show number",
		showMore: "Show more",
		authorAds: "All author's ads",
		similarAds: "Similar ads",
		featured: "Featured",
		productsAndServices: "Products and services",
		appoinments: "Appointments",
		personalData:
			"Your personal data and company data will not be transferred to third parties",
		companyType: "Choose company type",
		new: "New",
		acting: "Acting",
		name: "Name / company name",
		password: "Password",
		agree: "I agree to the terms of use and privacy conditions",
		servicesDoNotExist: "Services do not exist yet",
		adStats: "Ad Stats",
		views: "Views",
		messages: "Messages",
		weSentMessage:
			"We have sent a message to your phone number. To finish registration type the code in the message!",
		confirmationCode: "Confirmation code",
		register: "Register",
		myPage: "My page",
		services: "Services",
		logOut: "Log out",
		writeAMessage: "Write a message",
		companyRegistration: "Company registration",
		numberConfirmation: "Number confirmation",
		addAd: "Add ad",
		userAds: "User Ads",
		allPosts: "All posts",
		chooseSubcategory: "Choose a subcategory",
		featuredAds: "Featured Ads",
		profileSettings: "Profile Settings",
		editAd: "Edit Ad",
		online: "Online",
		categoriesDoNotExist: "Categories do not exist",
		all: "All"
	}
});

export default strings;
