import LocalizedStrings from "react-native-localization";

let strings = new LocalizedStrings({
	en: {
		products: "Goods and services",
		favorite: "Favorite",
		messages: "Messages",
		favorites: "Favorites",
		accaunt: "Accaunt",
		services: "Services",
		logout: "Logout",
		discount: "Discount available",
		fixedPrice: "Fixed price",
		placed: "created at",
		seeMore: "See more",
		description: "Description",
		salesDepartment: "Sales department",
		welcome: "Welcome to Forb",
		authorize: "Get authorized",
		withoutAuthorization: "Proceed",
		remember: "Remember",
		forgot: "Forgot password?",
		login: "Log in",
		noAccount: "Do not have an accaunt yet?",
		register: "Registration",
		proceed: "Proceed without authorization",
		agreement:
			"By loggin in you to your Account you accept the Terms of use of the Application",
		companyRegistration: "Registration of Company",
		believe: "Personal data of your company will not be distributed!",
		typeOfCompany: "Select type of company",
		new: "New",
		existing: "Existing",
		name: "Name / Company",
		email: "Email",
		organization: "Organization",
		responsible: "Responsible person",
		address: "Address",
		accept: "I accept the terms of",
		usage: "usage and conditions of confidentiality",
		next: "Next",
		sentMessage:
			"We have sent a message to your phone number. Type it in order to finish the registration",
		code: "Code",
		approve: "Approve",
		showNumber: "show number",
		allAds: "All ads of a user",
		similar: "Similar ads",
		typeMessage: "Type your message",
		productCard: "Product card",
		myAds: "My ads",
		payment: "Payment",
		statistics: "Statistics",
		cityOfServices: "City of services",
		saveChanges: "Save changes",
		profileSettings: "Profile Settings",
		favoriteAds: "Favorite Ads",
		noFavorites: "No favorites",
		noMessages: "No messages",
		allMessages: "All messages",
		createAd: "Create your add",
		selectCategory: "Select category",
		price: "Price (soums)",
		price_d: "Price (dollars)",
		title: "Type title",
		additionalFields: "Additional fields",
		name: "Name",
		value: "Value",
		yourDescription: "Your description",
		addPhoto: "Add photo",
		yourContacts: "Your contacts",
		publish: "Publish",
		activeAds: "Active ads",
		inactiveAds: "Inactive ads",
		adsDoNotExist: "Ads do not exist"
	},
	ru: {
		products: "Товары и услуги",
		favorite: "Избранное",
		messages: "Сообщения",
		favorites: "Избранные"
	},
	uz: {
		how: "Maxsulotlar va xizmatlar",
		favorite: "Tanlash",
		messages: "Xabarlar",
		favorites: "Tanlanganlar"
	}
});

export default strings;
